### ISSUE TITLE
MissingResponsePrototypeException thrown when using http-middleware 0.5.0 callable middleware

### ISSUE THREAD

**Issue by msheakoski** [zendframework/zend-stratigility#117]
The changelog says 
> Essentially, this means you can drop this package into an application targeting either the 0.4.1 or 0.5.0 versions of http-middleware, and it will "just work".

so I updated my app to use http-middleware to 0.5.0 and get this exception with zend-stratigility 2.1.0:

> Fatal error: Uncaught Zend\Stratigility\Exception\MissingResponsePrototypeException: Cannot wrap callable middleware; no Zend\Stratigility\Middleware\CallableMiddlewareWrapperFactory or Psr\Http\Message\ResponseInterface instances composed in middleware pipeline; use setCallableMiddlewareDecorator() or setResponsePrototype() on your Zend\Stratigility\MiddlewarePipe instance to provide one or the other, or decorate callable middleware manually before piping. in **zend-stratigility/src/MiddlewarePipe.php** on line **250**

Here is a small example to reproduce the error:
```php
<?php declare(strict_types=1);

use Interop\Http\Server\MiddlewareInterface;
use Interop\Http\Server\RequestHandlerInterface;
use Psr\Http\Message\ServerRequestInterface;
use Zend\Diactoros\Response\TextResponse;
use Zend\Diactoros\Server;
use Zend\Stratigility\MiddlewarePipe;
use Zend\Stratigility\NoopFinalHandler;

require __DIR__ . "/vendor/autoload.php";

$app = new MiddlewarePipe();

// Does NOT work, triggers an exception
$app->pipe(function (ServerRequestInterface $request, RequestHandlerInterface $handler) {
    return new TextResponse("Hello, world!");
});

// It works fine with classes though
$app->pipe(new class implements MiddlewareInterface {
    function process(ServerRequestInterface $request, RequestHandlerInterface $handler) {
        return new TextResponse("Hello, world!");
    }
});

Server::createServer($app, $_SERVER, $_GET, $_POST, $_COOKIE, $_FILES)
      ->listen(new NoopFinalHandler());
```

composer.json
```json
{
    "require": {
        "http-interop/http-middleware": "0.5.0",
        "php": "^7.1",
        "psr/http-message": "^1.0",
        "zendframework/zend-diactoros": "1.6.0",
        "zendframework/zend-stratigility": "2.1.0"
    }
}
```

**Comment by weierophinney** [comment]
Fixed with #118, with a release in 2.1.1.
