### ISSUE TITLE
Zend\Stratigility\MiddlewarePipe missing dependencies

### ISSUE THREAD

**Issue by datashuttle** [zendframework/zend-stratigility#137]
Instantiating a MiddlewarePipe instance fails on missing interface dependencies, namely:
Webimpress\HttpMiddlewareCompatibility\HandlerInterface, and
Webimpress\HttpMiddlewareCompatibility\MiddlewareInterface

### Code to reproduce the issue

use Interop\Http\Server\RequestHandlerInterface;
use Zend\Stratigility\{MiddlewarePipe, NoopFinalHandler};
use Zend\Diactoros\{Server, Response};
use Psr\Http\Message\ServerRequestInterface;

require __DIR__ . '/../vendor/autoload.php';

$pipe   = new MiddlewarePipe();

### Expected results
Pipe instance.

### Actual results
Fatal error on missing interfaces

**Comment by weierophinney** [comment]
How are you installing zend-stratigility, exactly? webimpress/http-middleware-compatibility, which provides these interfaces, is a direct requirement starting with 2.1.0. My suspicion is that these were not installed somehow, but I'm not sure why or how that could happen.

What are the results of `composer show`?

And what happens if you run `composer update`?

**Comment by datashuttle** [comment]
Yes Matt, here are the answers:

*Shell installed as:* composer require zendframework/zend-diactoros
zendframework/zend-stratigility. This should have pulled in the interfaces,
but they are missing in the webimpress/http-middleware-compatibility
namespace.

*composer show:*
doctrine/instantiator                    1.1.0 A small, lightweight utility
to instantiate objects in PHP without invoking their constructors
http-interop/http-server-handler         1.0.0 Common interface for HTTP
server-side request handler
http-interop/http-server-middleware      1.0.1 Common interface for HTTP
server-side middleware
myclabs/deep-copy                        1.7.0 Create deep copies (clones)
of your objects
phar-io/manifest                         1.0.1 Component for reading phar.io
manifest information from a PHP Archive (PHAR)
phar-io/version                          1.0.1 Library for handling version
information and constraints
phpdocumentor/reflection-common          1.0.1 Common reflection classes
used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock        4.2.0 With this component, a
library can provide support for annotations via DocBlocks or otherwise
retrieve information that...
phpdocumentor/type-resolver              0.4.0
phpspec/prophecy                         1.7.3 Highly opinionated mocking
framework for PHP 5.3+
phpunit/php-code-coverage                5.3.0 Library that provides
collection, processing, and rendering functionality for PHP code coverage
information.
phpunit/php-file-iterator                1.4.5 FilterIterator
implementation that filters files based on a list of suffixes.
phpunit/php-text-template                1.2.1 Simple template engine.
phpunit/php-timer                        1.0.9 Utility class for timing
phpunit/php-token-stream                 2.0.2 Wrapper around PHP's
tokenizer extension.
phpunit/phpunit                          6.2.4 The PHP Unit Testing
framework.
phpunit/phpunit-mock-objects             4.0.4 Mock Object library for
PHPUnit
psr/http-message                         1.0.1 Common interface for HTTP
messages
sebastian/code-unit-reverse-lookup       1.0.1 Looks up which function or
method a line of code belongs to
sebastian/comparator                     2.0.0 Provides the functionality
to compare PHP values for equality
sebastian/diff                           1.4.3 Diff implementation
sebastian/environment                    3.1.0 Provides functionality to
handle HHVM/PHP environments
sebastian/exporter                       3.1.0 Provides the functionality
to export PHP variables for visualization
sebastian/global-state                   2.0.0 Snapshotting of global state
sebastian/object-enumerator              3.0.3 Traverses array structures
and object graphs to enumerate all referenced objects
sebastian/object-reflector               1.1.1 Allows reflection of object
attributes, including inherited and non-public ones
sebastian/recursion-context              3.0.0 Provides functionality to
recursively process PHP variables
sebastian/resource-operations            1.0.0 Provides a list of PHP
built-in functions that operate on resources
sebastian/version                        2.0.1 Library that helps with
managing the version number of Git-hosted PHP projects
theseer/tokenizer                        1.1.0 A small library for
converting tokenized PHP source code into XML and potentially other formats
webimpress/composer-extra-dependency     0.2.2 Composer plugin to require
extra dependencies
webimpress/http-middleware-compatibility 0.1.4 Compatibility library for
Draft PSR-15 HTTP Middleware
webmozart/assert                         1.2.0 Assertions to validate
method input/output with nice error messages.
zendframework/zend-diactoros             1.7.0 PSR HTTP Message
implementations
zendframework/zend-escaper               2.5.2
zendframework/zend-stratigility          2.1.2 Middleware for PHP

composer update: no change

My guess is that the interfaces were not packaged for whatever reason.

Daryl


Daryl K. Wood, ZCE <http://www.zend.com/en/yellow-pages/ZEND014424>ZCA
<http://www.zend.com/en/yellow-pages/ZEND014424>
Chief Technology Officer
datashuttle.net <https://www.datashuttle.net>
linkedin <http://www.linkedin.com/in/datashuttle> | twitter
<http://twitter.com/datashuttle> | facebook
<http://www.facebook.com/daryl.wood.54>
PluralSight <http://www.pluralsight.com/author/daryl-wood> | Oreilly Media
<http://www.infiniteskills.com/authors/Daryl-Wood.html>
Adventure Blog <http://daryl-adventures.blogspot.com/>
Office: 208.503.3840

"In the sciences, new ideas are often judged for how far they lie outside
of the systems that scaffold our understanding of the world" — Claudia Geib
  How Much Should Expectation Drive Science?
<http://cosmos.nautil.us/short/161/how-much-should-expectation-drive-science>

**Comment by weierophinney** [comment]
webimpress/http-middleware-compatibility does not create any interfaces; instead it does some aliasing and declares some constants (see its [autoload shim](https://github.com/webimpress/http-middleware-compatibility/blob/master/autoload/http-middleware.php)). If the aliases are not being created, then it means the autoloaders it defines are not being dumped during installation.

Can you run a `composer dump-autoload` from your application root, please, and report the results after you have done so?

**Comment by datashuttle** [comment]
Okay, dumped the autoloader, no difference, so the aliases are missing.

Daryl

**Comment by weierophinney** [comment]
Honestly, not sure what to do at this point; I cannot recreate the issue from here:

1. `composer require zendframework/zend-stratigility zendframework/zend-diactoros`
2. Create the file `test.php` with the following contents:
   ```php
   use Zend\Stratigility\MiddlewarePipe;
   
   require 'vendor/autoload.php';

   $pipeline = new MiddlewarePipe();
   ```
3. Run `php test.php`

I get no errors.

Did you use the `--no-plugins` option when requiring zend-stratigility, by any chance? http-middleware-compatibility requires webimpress/composer-extra-dependency, which prompts for a version of http-interop/http-middleware to install. I specified 0.4.1 when I did so the first time; the second, I let it select the latest (0.5.0), but had the same results (no errors).

What version of composer are you using? You can get the latest by running `composer self-update`. This is the only other possible source of problems with installation that I can think of.

**Comment by datashuttle** [comment]
Ran the sample code in test.php = missing interfaces

updated composer

Ran the sample again = missing interfaces.

Did not use the --no-plugins option. Here's composer.json require:

"require": {
  "zendframework/zend-diactoros": "^1.7",
  "zendframework/zend-stratigility": "^2.1",
  "http-interop/http-middleware": "^0.5.0"
}

Very strange you cannot replicate. Hmm...

Daryl

**Comment by weierophinney** [comment]
This sounds like a composer issue, to be honest; it appears that the autoloader file that http-middleware-compatibility provides is not being installed.

**Comment by datashuttle** [comment]
Okay, I'm running global composer. Will try with a current composer.phar in
an empty project. Doesn't seem that would make any difference, but will try.

Daryl

**Comment by datashuttle** [comment]
Matt, it was the version installed globally causing the problem, even after
self-update. Not sure why, no matter.

The local version worked fine. Will update this so the issue can be closed.

Daryl

**Comment by weierophinney** [comment]
Glad you got it sorted, @datashuttle .
