### ISSUE TITLE
[3.0]MiddlewarePipe marked as `final`

### ISSUE THREAD

**Issue by webimpress** [zendframework/zend-stratigility#144]
On release-3.0.0 branch `MiddlewarePipe` is marked as `final`.

I have couple concerns about it, mainly the problem could be with testing, because we are not providing abstraction for the public interface. More I've wrote on discourse:
https://discourse.zendframework.com/t/rfc-expressive-3-design-changes/438/6

As discussed with @weierophinney on slack probably we should remove `final` or provide `interface`.

/cc @snapshotpl @danizord @xtreamwayz @weierophinney

**Comment by weierophinney** [comment]
Let's go with `MiddlewarePipeInterface` with the single method `pipe(MiddlewareInterface $middleware) : void`. Mocking this will be trivial, and we then only need to alter `MiddlewarePipe` to implement that interface.

**Comment by weierophinney** [comment]
Closed with #146
