### ISSUE TITLE
Wrong link in phpdoc

### ISSUE THREAD

**Issue by kelunik** [zendframework/zend-stratigility#147]
Seems like the `@see` at the top of https://github.com/zendframework/zend-stratigility/blob/release-3.0.0/src/MiddlewarePipe.php should link to https://github.com/senchalabs/connect instead of the current link, which results in a 404.

**Comment by webimpress** [comment]
@kelunik would you like to provide PR with the fix?

**Comment by kelunik** [comment]
Not really, have enough to do, just followed a link from Twitter. :-)
