### ISSUE TITLE
Question about marked a class as final

### ISSUE THREAD

**Issue by batumibiz** [zendframework/zend-stratigility#149]
Class is marked as final
https://github.com/zendframework/zend-stratigility/blob/release-3.0.0/src/MiddlewarePipe.php#L31
But Expressive extends it, which causes a critical error.
https://github.com/zendframework/zend-expressive/blob/master/src/Application.php#L27
Will Expressive be corrected?
Or will you be offered some other solution?
# #144

**Comment by Ocramius** [comment]
@batumibiz that's `master`. Expressive is still undergoing refactor to adapt to PSR-15

**Comment by batumibiz** [comment]
https://github.com/zendframework/zend-expressive/blob/release-3.0.0/src/Application.php
Branch 3.0.0 also tries to inherit

**Comment by froschdesign** [comment]
Is still under development!

See https://github.com/zendframework/zend-expressive/pull/543

**Comment by batumibiz** [comment]
Many thanks for the clarification.
I will wait.
The question is closed

**Comment by froschdesign** [comment]
> Many thanks for the clarification.

You are welcome! 😃
