### ISSUE TITLE
RuntimeException Layer and request path have gone out of sync for capitalised piped route

### ISSUE THREAD

**Issue by jakeBarwell** [zendframework/zend-stratigility#168]
Getting a RuntimeException
"Layer and request path have gone out of sync" 
From zendframework/zend-stratigility/src/Next.php line 271

### Code to reproduce the issue
Add piped route like this for example
    $app->pipe('/myadmin', \App\Middleware\Auth\AdminAuth::class);

Then via browser go to /MYADMIN
(Note the capital letters)

### Expected results
Either 404 or it matches that route
### Actual results
RuntimeException
"Layer and request path have gone out of sync"

**Comment by jakeBarwell** [comment]
Sorry that was on version 2.1.2 just upgraded to 2.2.1 and similar behaviour

Exception\PathOutOfSyncException thrown from src/Middleware/PathMiddlewareDecorator.php line 128

**Comment by weierophinney** [comment]
The patch prepared for master, #170, only includes the unit test, as the behavior was already correct in that branch.
