### ISSUE TITLE
[RFC] HTTP method overriding middleware

### ISSUE THREAD

**Issue by corentin-larose** [zendframework/zend-stratigility#171]
- [x] I was not able to find an [open](https://github.com/zendframework/zend-stratigility/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-stratigility/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [x] This is not a question. (Questions should be asked on [slack](https://zendframework.slack.com/) ([Signup for Slack here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

- Case 1: In my previous company which was handling several millions of request each day on a Restful API-centric website based on Apigility, we once realised that one of our customers just didn't allow other HTTP verbs than `GET` and `POST` through his proxy.
- Case 2: Some browser still don't allow other verbs than `GET` and `POST` in forms.

I propose to create a middleware overriding the HTTP method when `_method` parameter is provided in the `GET` or `POST` payload (ie `?_method=DELETE`).

Some options I also consider:
- Provide user with the ability to set the name of the parameter instead of the default name `_method`
- Provide the user with the ability to enforce that the argument has been provided in the super global (`$_GET` or `$_POST`) corresponding to the HTTP method used for the request (`GET` or `POST`)
- Provide user with the ability to decide whether argument should be removed from the query after usage (hence a cloned and modified query returned)

`validateMethod` has been derived from the request trait.

If interest shown, I will create the file and unit tests in a PR.
Should that middleware be provided as a "module"?

````php
<?php

declare(strict_types=1);

namespace Zend\Stratigility\Middleware;

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\MiddlewareInterface;
use Psr\Http\Server\RequestHandlerInterface;

class HttpMethodOverride implements MiddlewareInterface
{
    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler) : ResponseInterface
    {
        $method = $request->getAttribute('_method', null);

        if (!is_null($method)) {
            $this->validateMethod($method);

            $originalMethod = strtoupper($request->getMethod());

            switch ($originalMethod) {
                case 'GET':
                case 'POST':
                    $request = $request->withMethod(strtoupper($method));
                    break;
                default:
                    throw new InvalidArgumentException(sprintf(
                        'Only GET and POST http methods can be overrode, received %s',
                        $method
                    ));
            }
        }

        return $handler->handle($request);
    }

    /**
     * Validate the HTTP method
     *
     * @param null|string $method
     * @throws InvalidArgumentException on invalid HTTP method.
     */
    private function validateMethod($method)
    {
        if (! is_string($method)) {
            throw new InvalidArgumentException(sprintf(
                'Unsupported HTTP method; must be a string, received %s',
                (is_object($method) ? get_class($method) : gettype($method))
            ));
        }

        if (! preg_match('/^[!#$%&\'*+.^_`\|~0-9a-z-]+$/i', $method)) {
            throw new InvalidArgumentException(sprintf(
                'Unsupported HTTP method "%s" provided',
                $method
            ));
        }
    }
}

```

**Comment by corentin-larose** [comment]
Hello,

Yes, this is what I wanted to say when writing "Should that middleware be provided as a "module"?".
Ok, I will create a standalone package and come back to you guys for comments.
What do you think about the configuration options I proposed?
I will also come back with a standalone port of my zf-http-cache module.

**Comment by weierophinney** [comment]
Awesome to see it already exists! Make sure to contribute to it if you find it is missing functionality you need. :smile:
