### ISSUE TITLE
Compatibility with zend-httphandlerrunner and zend-diactoros

### ISSUE THREAD

**Issue by johnrobertporter** [zendframework/zend-stratigility#180]
I'm trying to understand the larger picture with the new layouts for the aforementioned packages and this one, and I can't get my head fully around it.

I may be missing something, but there seems to be a component missing to allow the `MiddlewarePipe` to be useable as the `ServerRequestHandlerInterface` requirement of `RequestHandlerRunner`?

In the older versions, we had the ability to simply pass a pipeline to stratigility and it run, but since these packages have rightly been abstracted, I can't figure out after reading them, how we are to run a pipeline without writing an intermediary handler.

I imagine that expressive has such a thing, but for the consumers who don't use expressive, would it be possible to have something created in the stratigility package?

**Comment by designermonkey** [comment]
This is why one shouldn't code at 11pm.
