### ISSUE TITLE
Introducing a common Error class?

### ISSUE THREAD

**Issue by bakura10** [zendframework/zend-stratigility#31]
Hi,

I've thought of something: currently, you can throw an exception with a message, and a code. This code is used to match a status code and return the appropriate error.

I like the idea of having the FinalHandler handle this and format the error response. If you want a different way to render your errors, just override the final handler and format them the way you want.

However, the issue is that it middlewares built around Stratigility don't have a common way to format errors. For instance, how a middleware that would need to return more than just a message would work? Some developers may decide to maybe encode using json_encode, and do custom logic in the FinalHandler, but it does not encourage a common design.

I'm suggesting that we would add a common interface:

```php
interface ResponseErrorExceptionInterface
{
    public function getMessage();

    public function getCode();

    /**
     * @return array
     */
    public function getExtra();
}
```

FinalHandler would be able to read this and create a response. Each middleware could use this exception. Then it's up to your ifnal handler to decide if you want to return the extra as "additional_details", "details", "error_extra" or whatever.

**Comment by weierophinney** [comment]
The signature of `FinalHandler` is:

```php
function (ServerRequestInterface $request, ResponseInterface $response, $err = null) : ResponseInterface
```

`$err` does not have any limits on type. This is on purpose. In Sencha Connect and in Express, what I saw happen was that middleware defined errors however they wanted, and documented how they delivered errors. Error middleware and/or the final handler could then handle them… or not. Essentially, if a handler cannot handle it, it pipes to the next; in the case of a final handler, it has sane defaults for reporting the error and/or creating a generic error response if it cannot handle it.

In Stratigility, you can raise an exception, or you can pass an exception via `$next()`… or you can pass a string, a code, a constant value, whatever. We're leaving it up to middleware developers to determine how they want to report errors, and *hoping* they'll document it and/or provide error handler middleware you can drop in for handling those errors.
