### ISSUE TITLE
MiddlewareRegexPipe class.

### ISSUE THREAD

**Issue by eguvenc** [zendframework/zend-stratigility#33]
What about regex support ? It can be more functional optionally if its support regex.

```php
$app = MiddlewarePipe('/api', $callable);

or i can use MiddlewareRegexPipe class.

$app = new MiddlewareRegexPipe('/admin/.*,  $callable)
```

**Comment by weierophinney** [comment]
We have no plans to add dynamic riding to Stratigility; this is a
middleware foundation only. Instead, we delegate that to applications or
third party projects; one such is [zend-expressive](
https://github.com/zendframework/zend-expressive).
