### ISSUE TITLE
Question regarding performance

### ISSUE THREAD

**Issue by harikt** [zendframework/zend-stratigility#4]
Hi @weierophinney , 

As stratigility can just route with static routes, I am thinking, it may be good if it can provide a router or a default router interface so that it can do dynamic routing and no one need to create another application / middleware to do the same.

I think your idea is to call 

```php
$app    = new MiddlewarePipe();
$app->pipe($zf2mvc);
$app->pipe($symfony2app);
$server = Server::createServer($app,
  $_SERVER,
  $_GET,
  $_POST,
  $_COOKIE,
  $_FILES
);
$server->listen();
```

etc. Though it looks nice, I wish if it can have dynamic routing built by default so the overhead of looking the routes and dispatching can be reduced.

Thank you.

**Comment by weierophinney** [comment]
The plan is to keep Stratigility purposely bare-bones. The current static routing is really only present to allow segregating different applications; if you want dynamic routing, you would do so in middleware you pipe into the stack. This will also be beneficial in allowing multiple types of routing capabilities, allowing developers to pick the router that works best for their needs.

**Comment by mtymek** [comment]
BTW, hypothetical question: what if I wanted to segregate different applications by subdomain, and not path?

**Comment by weierophinney** [comment]
@mtymek — Stratigility's routing is strictly path-based. In the case of segregating applications by subdomain, you'd have to do that in dedicated middleware that's attached without a path.

The approach in this library is exactly the same as with [Connect](https://github.com/senchalabs/connect); it's usable on its own, but is really meant as a foundation for a microframework to build on. That's the intent.

**Comment by harikt** [comment]
Hi @weierophinney , 

What about creating a base interface for router, so that any router that complies with the interface can be plugged in ?

I did played earlier with conduit and from my experiments ( https://github.com/cocoframework/Cocoframework.ApplicationMiddleware ) what I understood is if you are building a middleware with a different router that middleware can itself act as an application .

So I would like stratigility router to be able to handle it. ( As I said like , which is a good thing I believe and which will help not to invent another middleware )

Thank you.

**Comment by mindplay-dk** [comment]
@harikt the middleware API already has (or rather, is) a universal interface for routers, dispatchers, anything you can think of. I think there is not much point inventing APIs for specific types of middleware when the middleware API itself can already accommodate just about anything you can dream up - including routers with wildly different semantics and strategies. Integrating my own router was [dead easy](https://gist.github.com/mindplay-dk/11e7c08ff6aa4d3486a4) - and fun :-)

**Comment by harikt** [comment]
Hey @mindplay-dk ,

I have already played with something similar to your work. See my comments above. What I feel is in that case you don't really need a middleware pipe just to pipe it.

**Comment by mindplay-dk** [comment]
@harikt I guess that depends on why you're using a middleware stack in the first place. For me, it's an extra top layer, providing a higher degree of control. And that's pretty much it. To me, it's a utility layer - like, for one, providing more control than, say, .htaccess rewrites, and eliminating most of the dependency on control at the level outside of the programming language.
