### ISSUE TITLE
Add support for PHP 7's error exceptions

### ISSUE THREAD

**Issue by msheakoski** [zendframework/zend-stratigility#42]
Since PHP 7 now [converts errors into exceptions](http://php.net/manual/en/language.errors.php7.php), it would be useful to add a `catch (Error $e)` to https://github.com/zendframework/zend-stratigility/blob/master/src/Dispatch.php#L83-L85 so that non-thrown errors like `1/0` are also caught and sent to error middleware.

This is very useful for using middleware to send errors to Sentry or display them in Whoops or BooBoo.

**Comment by msheakoski** [comment]
Just in case anybody needs a quick hack to work around this issue, I moved the initialization of Whoops into the middleware's constructor, which causes `set_error_handler()` to be called when the middleware is added to `$app->pipe(new WhoopsMiddleware)`. Because Whoops's internal error handler converts errors into exceptions, the "ErrorException" gets handled the same way as thrown exceptions.

```php
<?php // WhoopsMiddleware.php

use Psr\Http\Message\ResponseInterface as Response;
use Psr\Http\Message\ServerRequestInterface as Request;
use Whoops\Handler\PrettyPageHandler;
use Whoops\Run;
use Zend\Diactoros\Response\HtmlResponse;
use Zend\Stratigility\ErrorMiddlewareInterface;

class WhoopsErrorHandler implements ErrorMiddlewareInterface
{
    protected $whoops;

    public function __construct()
    {
        $this->whoops = new Run;
        $this->whoops->pushHandler(new PrettyPageHandler);
        $this->whoops->register();
    }

    public function __invoke($error, Request $request, Response $response, callable $next = null)
    {
        $method = Run::EXCEPTION_HANDLER;
        ob_start();
        $this->whoops->$method($error);
        return new HtmlResponse(ob_get_clean(), 500);
    }
}
```

**Comment by nesl247** [comment]
Looks like there is a PR for this #49.

**Comment by Ocramius** [comment]
Marking as duplicate
