### ISSUE TITLE
FinalHandler should not display stack traces by default

### ISSUE THREAD

**Issue by michaelmoussa** [zendframework/zend-stratigility#45]
[This](https://github.com/zendframework/zend-stratigility/blob/1.1.2/src/FinalHandler.php#L117-L121) seems like a dangerous default to me, and it contradicts the Expressive documentation [here](https://github.com/zendframework/zend-expressive/blob/1.0.0/doc/book/features/error-handling.md#error-handling).

Specifically:

> If the FinalHandler was initialized with an option indicating that it is in development mode, it writes the exception stack trace to the response body.

However, the default initialization of the `FinalHandler` (which is [what Expressive does](https://github.com/zendframework/zend-expressive/blob/2db114f9c888e5ce06c808c44c47f70324be4d5c/src/ErrorMiddlewarePipe.php#L73) in the default error pipeline) leaves the `env` option unset, which causes `! isset($this->options['env'])` to evaluate to `true` and creates the Development error message. You'd actually _need_ to specify `['env' => 'production']` in the constructor in order to _not_ display the stack trace.

I think the reverse would be a safer default - you must explicitly state that you're in development in order for the stack trace to appear (which is what the Expressive documentation indicates).

Specifically: `if (isset($options['env']) && $options['env'] === 'development')`

Either that, or correct the Expressive documentation.

I like the former better, but I realize it's _technically_ a BC break (if your application needs to display stack traces in Production by default, that is...), so it should be discussed (assuming I'm not the only one who thinks this is an issue).

Thoughts?

**Comment by weierophinney** [comment]
Definitely a bug. While it's a BC break, the defaults should always be production-safe, so I'd consider the current behavior a bug. Users can adapt if they need to have the stack trace displayed.

Send me a PR! :+1:
