### ISSUE TITLE
Regression on 1.2.0 with Response end

### ISSUE THREAD

**Issue by bakura10** [zendframework/zend-stratigility#50]
Starting from version 1.2, our app stopped working when an error is thrown in the code.

In our code, the `FinalHandler` is map to a custom handler:

```php
class JsonErrorHandler
{
    public function __invoke(ServerRequestInterface $request, ResponseInterface $response, $err = null)
    {
        if ($err) {
            return $this->handleError($err, $response);
        }

        if (null === $request->getAttribute(RouteResult::class)) {
            return new JsonResponse(['message' => 'Not Found'], 404);
        }

        return $response;
    }

    private function handleError($err, ResponseInterface $response)
    {
        // To avoid security issue, when the error is an exception, we simply display a 500
        if ($err instanceof Exception) {
            return new JsonResponse(['message' => 'An error occurred'], 500);
        }

        return new JsonResponse(['message' => $response->getReasonPhrase()], $response->getStatusCode());
    }
}
```

It used to return a JsonResponse when there was an error, but now it throws the RuntimeException error:

<img width="1677" alt="capture d ecran 2016-03-21 a 16 18 53" src="https://cloud.githubusercontent.com/assets/1198915/13923368/a1b9a49e-ef80-11e5-8808-e9f0b8d0ed5c.png">

**Comment by weierophinney** [comment]
As noted in the 1.2 release notes, if you call any `with()` methods after calling `$response->end()`, an exception is now raised. Can you grep through your code to see if you're doing that, please?

**Comment by bakura10** [comment]
Actually it looks like I'm another issue : my FinalHandler is never executed... Not sure to undesrtand why, I'm still debugging it.

**Comment by bakura10** [comment]
I've checked all my code and there is no ->with() :(. Still debugging...

**Comment by bakura10** [comment]
I've been able to trace it. The error comes from the Service Manager. $container->has('Zend\Expressive\FinalHandler') returns false...

**Comment by bakura10** [comment]
Okay, found my problem and may be due to a clean on our end of dependencies. Sorry :p.

**Comment by nesl247** [comment]
@bakura10 Can you tell me what your issue was? I'm experiencing the same issue except I have a few middleware that execute `with()`. However, even when I disable that middleware the error occurs.

**Comment by nesl247** [comment]
@weierophinney I did track it down to `SapiEmitterTrait` setting the `Content-Length` header causing my specific issue. Though why is another question.

**Comment by bakura10** [comment]
The issue on my end was stupid: I aliased the "Zend\Expressive\FinalHandler" to a class of mine, but I forgot to add this class inside the "factories" key, so the service manager was unable to create it.

As mwop said, can you do a search in your code to check if you're not doing a prohibited ->with* call somewhere?

**Comment by nesl247** [comment]
I believe I've tracked the issue down to the built in final handler actually being broken because the SapiEmitter adds the Content-Length after it's called. For some reason `500 OK` is actually what I'm getting if I comment out the with line in the emitter, so this `OK` bit is wrong for one.

**Comment by weierophinney** [comment]
@nesl247 that will only be an issue if you've called `$response->end()` previously; otherwise, those exceptions cannot and will not be raised. Look for that call specifically.

**Comment by nesl247** [comment]
@weierophinney I figured out the issue, and it's not a bug I can fix. If `FinalHandler` is called for an error, this bug will always happen because the `SapiEmitterTrait` will inject the `Content-Length` before it emits the response.

**Comment by bakura10** [comment]
Actually I had also this 500 OK @nesl247 . How are you catching exceptions to display them?

Here is the code I'm doing:

Add this custom handler (adapt to your need):

```php
<?php

use Exception;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Zend\Diactoros\Response\JsonResponse;
use Zend\Expressive\Router\RouteResult;

class JsonErrorHandler
{
    /**
     * @var bool
     */
    private $production;

    /**
     * @param bool $production
     */
    public function __construct(bool $production)
    {
        $this->production = $production;
    }

    /**
     * @param ServerRequestInterface $request
     * @param ResponseInterface      $response
     * @param mixed|null             $err
     * @return ResponseInterface
     */
    public function __invoke(ServerRequestInterface $request, ResponseInterface $response, $err = null)
    {
        if ($err) {
            return $this->handleError($err, $response);
        }

        if (null === $request->getAttribute(RouteResult::class)) {
            return new JsonResponse(['message' => 'Not Found'], 404);
        }

        return $response;
    }

    /**
     * @param  mixed             $err
     * @param  ResponseInterface $response
     * @return JsonResponse
     */
    private function handleError($err, ResponseInterface $response)
    {
        // To avoid security issue, when the error is an exception, we simply display a 500
        if ($err instanceof Exception) {
            return new JsonResponse(['message' => $this->production ? 'An error occurred' : $err->getMessage()], 500);
        }

        return new JsonResponse(['message' => $response->getReasonPhrase()], $response->getStatusCode());
    }
}
```

Add it to your config:

```php
'dependencies' => [
        'aliases' => [
            'Zend\Expressive\FinalHandler'       => JsonErrorHandler::class,
        ],
        'factories' => [
            JsonErrorHandler::class                  => JsonErrorHandlerFactory::class
        ],
    ],
```

You can then define a simple JsonErrorHandlerFactory that just inject the production attribute.

**Comment by nesl247** [comment]
@bakura10 https://github.com/zendframework/zend-stratigility/issues/51 is the issue for the `500 OK` style message. I'm not intent on replacing the `FinalHandler` with something custom. It should work out of the box otherwise it doesn't serve a purpose.

**Comment by nesl247** [comment]
Moving this to a new specific issue #53.
