### ISSUE TITLE
FinalHandler always uses `OK` as reasonPhrase if non previously set

### ISSUE THREAD

**Issue by nesl247** [zendframework/zend-stratigility#51]
If an error makes it to `handleError`, without a `reasonPhrase`, it will always be `OK`. This is because when calling `withStatus`, it is passing `getReasonPhrase` which checks if there is one set, and if not uses it from the current `statusCode`. Of course `statusCode` is 200 at that time because it's the default in the constructor.

**Comment by michaelmoussa** [comment]
I believe #52 will resolve this, @nesl247 /cc @weierophinney
