### ISSUE TITLE
FinalHandler and env option.

### ISSUE THREAD

**Issue by potfur** [zendframework/zend-stratigility#57]
> `env`, the application environment. If set to "production", no stack traces will be provided.

In reality, same will happen also when `env` is not set at all or _falsy_.

It would be nice to change `FinalHandler` behaviour to mute stack traces when `env` is set to `production` (const for that would be also nice), but this would break BC.

Another solution would be to drop `env` completely in favour of callable creating response message from passed error - effectively replacing `::createDevelopmentErrorMessage`.
It would also allow xdebug users to create their own formatters.
But this is more _in future_.

So for now, probably docs update would do.

**Comment by moderndeveloperllc** [comment]
@potfur If you check the `2.0.0-dev` branch, you will see that `FinalHandler` is going away, so I doubt there will be much movement on this. 2.0 will come with [default error-handling middleware](https://github.com/zendframework/zend-stratigility/blob/dev-2.0.0/src/Middleware/ErrorHandler.php) that allow you to set error output "generators". You would be able to pass/check variables in those to determine output format.

**Comment by potfur** [comment]
@moderndeveloperllc thanks for pointing it - this actually solves my issue.
:+1:
