### ISSUE TITLE
Move Interfaces into New Package

### ISSUE THREAD

**Issue by schnittstabil** [zendframework/zend-stratigility#90]
As far as I can see, Stratigility declares 3 interfaces:
* `Zend\Stratigility\Http\ResponseInterface`
* `Zend\Stratigility\Http\ErrorMiddlewareInterface`
* `Zend\Stratigility\Http\MiddlewareInterface`

The first two will be removed with 2.0.0, the last one will introduce a BC if #15 get accepted.

Interfaces are nice, as long as they allow interoperability, but as long as they are bundled with a concrete implementation consumers cannot reuse their work in other projects.

It would be really nice if you may consider to move those interfaces into a new package, e.g. `zendframework/zend-stratigility-contracts` and release a 1.3 version. If time comes to release 2.0, just release a contracts 2.0 version as well.

Thus, middlewares can require `"zendframework/zend-stratigility-contracts" : "^1.3 || ^2.0"` in their `composer.json` files…

**Comment by xtreamwayz** [comment]
#15 is 1.5 years old and obsolete. As it currently stands, it's already accepted in develop (v2.0):

```php
interface MiddlewareInterface
{
    public function __invoke(Request $request, Response $response, callable $next);
}
```

**Comment by schnittstabil** [comment]
> #15 is 1.5 years old and obsolete.

#15 is still a 2.0.0 milestone and not closed, thus it looks like that it is still a topic for discussion.

---

I don't argue about your BC design decision at all, but:
* Some interfaces may be added/changed in version 3.0 as well.
* If a package relies only on your interfaces it can use `zend-stratigility-contracts`, and `zend-stratigility` does not need to be installed – thus composer dependency conflicts can simply not arise.
* If a project wants to share code between different environments, e.g. like the *Zend Framework* and *Stratigility*, then a *interface-only* package will help them to organize their code.

Therefore, I think right now, just before 2.0.0 will land, would be the right time to refactor the interfaces out.

**Comment by weierophinney** [comment]
The point is that we plan to _remove_ these interfaces entirely for the 2.0 release, and we've marked most of these deprecated, with the exception of `MiddlewareInterface`, which we will deprecate in the next minor release.

It's not a topic for discussion; it's a decision already made. We plan to abandon these interfaces, in favor of those proposed in http-interop/http-middleware; we're simply waiting to release 2.0 until the dust has settled on that project and we're reasonably certain there will be no more changes, or none that would require BC breaks for us to accommodate.
